#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --time=02:20:00

export CRAFT=/home/ban115/craft/craft/
export PATH=$CRAFT/cuda-fdmt/cudafdmt/src:$CRAFT/python:$PATH
export PYTHONPATH=$CRAFT/python:$PYTHONPATH
export OMP_NUM_THREADS=8

module unload PrgEnv-cray
module load python/2.7.10
module load astropy

thedir=$1
thebase=`basename $thedir`
indir=/scratch2/askap/askapops/craft/SB*
ls -d $indir | parallel -j 48 $CRAFT/jobs/summarise_sb.job
